# Permalinks
#permalink:        pretty
relative_permalinks: true

# Setup
title:            Thomas Freudenberg
tagline:          'Confessions of a caffeine addict'
description:      'Confessions of a caffeine addict'
imageurl:         '/public/tfr.jpg'
url:              //thomasfreudenberg.com

author:
  name:           'Thomas Freudenberg'
  url:            https://twitter.com/thoemmi

disqus_short_name: thomasfreudenberg
disqus_show_comment_count: true

google_analytics_tracking_id: UA-262965-1

paginate:         5
permalink:        /archive/:year/:month/:day/:title/
paginate_path:    "page/:num"

only_frontmatter_categories: true

redirect_generate_aspx: true

exclude:
  - _pretzel
  - deploy.cmd
  - .gitignore
  - .git
