# Permalinks
#permalink:        pretty
relative_permalinks: true

# Setup
title:            Thomas Freudenberg
tagline:          'Confessions of a caffeine addict'
description:      'Confessions of a caffeine addict'
imageurl:         '/public/tfr.jpg'
url:              http://thomasfreudenberg.com

author:
  name:           'Thomas Freudenberg'
  url:            https://twitter.com/thoemmi

disqus_short_name: thomasfreudenberg
disqus_show_comment_count: true

google_analytics_tracking_id: UA-262965-1

paginate:         5
permalink:        /archive/:year/:month/:day/:title/
paginate_path:    "page/:num"

markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "highlight"]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
